# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWyChhC3GjfGSsrHjFb3zFSIMDF8CAIa
"""

pip install -U sentence-transformers



from pandas import *
#added this part for reading data from my drive - Sabrina
import os
from google.colab import drive
#drive.mount('/content/drive/')
#please change the data path
data = read_csv("ds.csv")

sentences = data['Sentence'].tolist()

print(sentences)

sentence_embeddings = model.encode(sentences)

import pandas as pd
import numpy as np
df = pd.DataFrame()

for sentence, embedding in zip(sentences,  sentence_embeddings):
    print("Sentence:", sentence)
    #print("Embedding:", embedding)
    list1 = list(embedding)
    print(list1)
    df1 = pd.DataFrame([list1])
    df = df.append(df1, ignore_index=True)
  
df.to_csv('a2.csv')
   
    #print("")

#import pandas as pd
#import numpy as np
#DF = pd.DataFrame(embedding)
#DF.to_csv("data1.csv")