# -*- coding: utf-8 -*-
"""Copy of Copy of Missing data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_AMwW5JNG9M3pWaK16ejyVh7f4VKStD
"""

import pandas as pd
df = pd.read_csv('DS.csv')

df = df.drop(['C'], axis=1)

df.isnull()

df.isna().sum()

from sklearn.impute import KNNImputer

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
df.head()

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df = pd.DataFrame(imputer.fit_transform(df),columns = df.columns)
df.to_csv('out.csv', index=False)